name: Nodejs CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.18.2"
      - name: Install node_modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Setup Finish
        run: echo "Finished!"
